WIP: feat: Added "--allow-uppercase-in-optional-scope" opt. arg. Tests-todo
espressif/conventional-precommit-linter pull request #26
Opened 2024-06-07 09:04 UTC by petermESP

Added "--allow-uppercase-in-optional-scope". Overrides test ['error_scope_capitalization'] with an adjusted regex. See code.

2024-06-07 10:23 UTC, tomassebestik commented
(Normally, we don't review PRs marked as WIP/Draft. PRs should be in a "ready to merge" state before requesting human reviews.)

This PR is missing a lot of items. Please read the [Contributing Guide](https://github.com/espressif/conventional-precommit-linter/blob/master/CONTRIBUTING.md) and make the necessary fixes:
- Missing tests
- Changes in style without updated thumbnails
- Missing documentation (README.md)
- Missing link to the GitHub issue
- Missing related internal JIRA ticket number; **NOT a link**, just a plain text number like `JIRA-123`

2024-06-07 10:23 UTC, tomassebestik requested changes

2024-06-07 10:23 UTC, tomassebestik commented on conventional_precommit_linter/hook.py
> +    parser.add_argument('--allow-uppercase-in-optional-scope', action='store_true', help='Allow uppercase letters in the optional scope.')
This is too long .... can you please change it to something more reasonable (e.g. `--scope-case-insensitive`)

2024-06-07 10:23 UTC, tomassebestik commented on conventional_precommit_linter/hook.py
> +            f"{_get_icon_for_rule(rules_output_status['error_scope_capitalization'])} {_color_red('overridden with --allow-uppercase-in-optional-scope')} {_color_blue('(<optional-scope>)')} if used,
This output message is confusing.

1) `overridden with --allow-uppercase-in-optional-scope` part is not necessary and breaks the output format style
2) if the condition changed, then also output message should change

I suggest something like `if used, must be written without whitespace.` for that case.

2024-06-07 10:23 UTC, tomassebestik commented on conventional_precommit_linter/hook.py
> +            f"{_get_icon_for_rule(rules_output_status['error_scope_capitalization'])} {_color_blue('(<optional-scope>)')} if used, must be written in lower case without whitespace. Use '--allow-upper
Remove `Use '--allow-uppercase-in-optional-scope' to override.`.

The output message for the user should be direct and simple. These extra options are described in the documentation.

2024-06-12 15:06 UTC, petermESP commented
> (Normally, we don't review PRs marked as WIP/Draft. PRs should be in a "ready to merge" state before requesting human reviews.)
> 
> This PR is missing a lot of items. Please read the [Contributing Guide](https://github.com/espressif/conventional-precommit-linter/blob/master/CONTRIBUTING.md) and make the necessary fixes:
- [x] Missing tests
- [ ] Changes in style without updated thumbnails / thumbnails in PR description
   - @tomassebestik Thumbnails in PR description?
- [x] Missing documentation (README.md)
- [x] Missing link to the GitHub issue
- [x] Missing related internal JIRA ticket number; **NOT a link**, just a plain text number like `JIRA-123`

2024-06-13 07:49 UTC, tomassebestik commented
Code looks good, nice job with improving test framework. LGTM

Add please to the commit message body `Closes https://github.com/espressif/conventional-precommit-linter/issues/25`

2024-06-13 10:28 UTC, merged